### ISSUE TITLE
Blog post and thank

### ISSUE THREAD

**Issue by eu-hugo** [ru-lai/ama#1]
Hi there!
I added your chrome extension to block youtube bs, which led me to its Chrome Extensions webpage, which led me to the buy-me-a-coffee link, which led me to your personal blog, which led me to your posts about SRS.

Just acknowledging all of that and saying thanks, much of what you wrote, your history, your views, etc, resonated with me.

Thanks! Bye!

**Comment by nnashwin** [comment]
@h-rds You're welcome.
